### PR TITLE
Reference Manual

### PR DESCRIPTION
**Pull request by JSousa-UoL**
Github Action added to generate reference manual based on ukat docstrings and make it available online.

`doc` folder contents deleted, only README.md file was kept.

### CODE REVIEW

**Comment by alexdaniel654** [comment]
Yep, all looks good to me. Its obviously a bit bare bones, but any online documentation is better than no online documentation! Nice work.

**Comment by alexdaniel654** [comment]
Sorry, I know I just merged this. I was then pondering some more. Perhaps it would make more sense to generate the documentation on a new tag rather than push to master as new tags are what causes a new version on PyPI i.e. the current system could lead to the documentation being ahead of the code people are actually installing.

**Comment by JSousa-UoL** [comment]
Hi @alexdaniel654 , thanks for your feedback. You have a good point about the documentation potentially be ahead of the release version/tag. Maybe you could edit the "dev" branch directly without a PR. You could replace:

'''
on:
     push:
'''

with

'''
on:
  release:
    types: [published]
'''

**Comment by alexdaniel654** [comment]
Maybe we could be even more specific and say only tags on the master branch. When I've been prototyping things with actions that run on version tags on other repos, I use release candidates, these end up on PyPI but aren't the default people would download but the snipped you suggested above would update the documentation for each one of them.
image

**Comment by JSousa-UoL** [comment]
I see, I wasn't aware of the release candidate situation. So maybe use a similar intro code to "new_release.yaml" and add tags-ignore?

```
on:
  push:
    tags:
    - 'v*'
    tags-ignore:
    - '.*rc.*'
 ```

**Pull request merged**
