### PR TITLE
fetch.py without using specific filepaths

### PR DESCRIPTION
**Pull request by JSousa-UoL**
This PR is an attempt at solving one of the topics discussed in issue #72. 

fetch.py was modified so that it doesn't use specific filepaths anymore. "tests" folder in "data" was also removed as it wasn't being used and there are no plans for it to be used in the future.

### CODE REVIEW

**Comment by alexdaniel654** [comment]
I think it would be a good idea to have some tests for this. I had to checkout this branch and run all the notebooks to check that it works. That process could easily be automated by having a normal test that would fetch each available dataset, check it has the correct number of files then compare the arraystats to a known ground truth.

**Comment by alexdaniel654** [comment]
The tests for the mapping classes that use this data are designed to test the output of the post-processing. Admittedly, if the input data has changed then they will also fail, but that's another reason to test the input data here. If a test in a mapping class fails but the data fetched doesn't fail then you know its an issue with the mapping class, if both fail then you know its an issue with the data. This helps with debugging and keeps the scope of each test smaller which is one of the main aims of unit testing. At the moment if there is an error in this data fetching code then it only shows itself in tests in the mapping module which is very counterintuitive.

In an ideal world we would have one bit of code that's responsible for fetching the data (but doesn't care what its fetching) and another bit of code that is responsible for tracking the data itself. These would be tested independently with the former tested the way you're suggesting and the latter tested the way I'm suggesting. Re-writing in this style would be relatively time consuming and I don't think it's a priority at the moment however, as this code is doing both of these jobs, I think having both testing methodologies is important.

**Comment by JSousa-UoL** [comment]
Thanks for the comment @alexdaniel654, I will draft the fetch_test.py this afternoon and then we can see what's missing and approve if we're happy with it.

**Comment by JSousa-UoL** [comment]
Just finished writing the fetch_test.py. Feel free to comment and I'll make the necessary corrections so that we can move on to the first release w/ Zenodo

**Review by alexdaniel654 — APPROVED** [review]
Looks good to me

**Pull request merged**
